### ISSUE TITLE
Problems with go2rtc configuration

### ISSUE THREAD

**Issue by THorst92** [felipecrs/dahua-vto-on-home-assistant#15]
Hi, 

thank you for sharing your configuration!
I have a question concerning problems with my go2rtc configuration.
I copied the go2rtc config:

```
streams:
  cam_2way_sd:
    # H264
    - echo:/config/scripts/vto_setup_stream_new.sh
      ffmpeg:rtsp://admin:password@xx.xx.xx.xx/cam/realmonitor?channel=1&subtype=0#video=copy
    # PCMA, 2-way audio
    - echo:/config/scripts/vto_setup_stream_new.sh
      rtsp://admin:password@xx.xx.xx.xx/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif#media=audio#backchannel=1
    # AAC
    - rtsp://127.0.0.1:8554/cam_hd?audio=aac
 cam_hd:
    # H264, AAC
    - echo:/config/scripts/vto_setup_stream_new.sh
      ffmpeg:rtsp://admin:password@xx.xx.xx.xx/cam/realmonitor?channel=1&subtype=1#video=copy#audio=copy
    # PCMA
    - rtsp://127.0.0.1:8554/cam_2way_sd?audio=pcma&backchannel=0
 ```

Unfortunately I cannot see the stream when I click on "stream" in go2rtc and get the following log:

```
09:29:41,381 | warn | [rtsp] error=streams: read tcp 127.0.0.1:51616->127.0.0.1:8554: i/o timeout stream=cam_2way_sd
09:29:42,020 | warn | [rtsp] error=streams: read tcp 127.0.0.1:51618->127.0.0.1:8554: i/o timeout stream=cam_hd
09:29:42,020 | warn | undefined error=write tcp 127.0.0.1:8554->127.0.0.1:57624: write: broken pipe caller=github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:260
09:29:52,022 | warn | [rtsp] error=streams: read tcp 127.0.0.1:53318->127.0.0.1:8554: i/o timeout stream=cam_hd
09:30:02,023 | warn | undefined error=write tcp <go2rtc_ip>:8554-><frigate_ip>:56512: write: broken pipe caller=github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:260
09:30:11,483 | warn | [rtsp] error=streams: read tcp 127.0.0.1:36384->127.0.0.1:8554: i/o timeout stream=cam_2way_sd
09:30:11,483 | warn | undefined error=write tcp 127.0.0.1:8554->127.0.0.1:39554: write: broken pipe caller=github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:260
```

For Frigate and Home Assistant camera card it seems to work.
Do you have an idea why I get the errors?

Best reagrds,

Thorsten

**Comment by felipecrs** [comment]
How are you running go2rtc? Through the [add-on](https://github.com/AlexxIT/hassio-addons)? Which version of go2rtc?

I'm specially confused about this:

```
tcp <go2rtc_ip>:8554-><frigate_ip>:56512:
```

Why did you mention Frigate IP? I thought you were not running Frigate.

---

@THorst92, even if you get past that, you'll bump into this issue:

- https://github.com/dermotduffy/advanced-camera-card/issues/1984

**Comment by THorst92** [comment]
go2rtc (Version 1.9.9) is running as add-on in Home Assistant.
Frigate (I'm using it, maybe it was written unclear) is running in a separate LXC container with docker, this is the reason Frigate has another IP than go2rtc. 
Frigate is running separate to have the videos stored in another location than HomeAssistant. I've not using go2rtc in Frigate because I've not go into detail to run the script in the Frigate docker container.

Currently I have another script version running:
```
#!/bin/bash
set -euo pipefail

readonly admincreds='admin:password'
readonly onvifcreds='admin:password'
readonly host='<dahua_ip>'
readonly path="${1}"

params=""
params+="&Encode[0].MainFormat[0].Audio.Compression=G.711A" # Chrome WebRTC backchannel codec restrictions.
params+="&Encode[0].MainFormat[0].Audio.Frequency=8000" # Chrome WebRTC backchannel codec restrictions.
params+="&Encode[0].MainFormat[0].Audio.Bitrate=64"
params+="&Encode[0].ExtraFormat[0].Audio.Compression=AAC" # For use with Frigate
params+="&Encode[0].ExtraFormat[0].Audio.Frequency=16000"
params+="&Encode[0].ExtraFormat[0].Audio.Bitrate=64"

params+="&Encode[0].MainFormat[0].Video.GOP=4" # Optional, read considerations

curl --fail --silent --show-error --digest --globoff --user "${admincreds}" \
  "http://${host}/cgi-bin/configManager.cgi?action=setConfig${params}" >&2

echo "rtsp://${onvifcreds}@${host}${path}"
```

With the following go2rtc configuration:
```
streams:
  gt01_klingel_2way_sd:
    # MainFormat: PCMA/8000, 2-way audio, H264
    - echo:/config/scripts/vto_setup_stream.sh /cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif

  gt01_klingel_hd:
    # ExtraFormat: MPEG4-GENERIC/16000, H264
    - echo:/config/scripts/vto_setup_stream.sh /cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif#media=audio+video#backchannel=0
```

Unfortunately with this setting I'm not able to get the microphone working with the advanced camera card. It's only working with the WebRTC-Card.
Also in Frigate I am not able to get audio (as well as 2way audio) working.
