### ISSUE TITLE
Audio drift in two-way communication, increasing delay over time with microphone enabled

### ISSUE THREAD

**Issue by Xeudoron** [felipecrs/dahua-vto-on-home-assistant#8]
Hello,

First off, thanks for putting together such a great resource on this topic. After some tinkering, I managed to get two-way communication working with Frigate, and then in Home Assistant.

**Setup Details:**
- VTO: DHI-VTO2211G-WP
- Firmware: 4.700.0000000.2.R,build:2024-08-29
- Both Frigate an HA I have behind reverse proxy with TLS
  _I access Frigate directly via https://nvr.example.com and HA via https://ha.example.com (even the mobile companion app)_

Some notes:
- I upgraded the VTO firmware from 4.5 to 4.7 using [config tool](https://dahuawiki.com/ConfigTool). The Toolbox method didn’t work—it also seemed to need a cloud account.
- To get two-way communication working, I had to enable HTTPS for HA, both in the browser and the companion app.

**Frigate config**

```
go2rtc:
  streams:
    doorbell:
      - echo:/config/scripts/fix_vto_codecs.sh
      - rtsp://admin:admin@192.168.0.100/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&backchannel=0
#          input_args: preset-rtsp-restream-low-latency
#          roles:
#            - detect
#            - record
#      output_args:
#        record: preset-record-generic-audio-copy
```
**Home Assistant Frigate card**
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.doorbell
    live_provider: go2rtc
menu:
  style: outside
  buttons:
    display_mode:
      enabled: true
    mute:
      enabled: true
    microphone:
      enabled: true
      priority: 49
      alignment: opposing
    media_player:
      enabled: false
    timeline:
      enabled: false
    fullscreen:
      enabled: false
    camera_ui:
      enabled: false
    download:
      enabled: false
    snapshots:
      enabled: false
    clips:
      enabled: false
    live:
      enabled: false
    frigate:
      enabled: false
  button_size: 80
```

**Current Issue:**

When I enable the mic in Frigate/HA, the audio from the VTO to my speaker gradually gets delayed throughout the session. Initially, the delay is acceptable, but over time, it becomes noticeably worse. Interestingly, the person at the VTO hears me without significant delay throughout.

Oddly enough, when I open Frigate on both my phone and desktop simultaneously, and use the mic on my phone while listening on my desktop, the audio works with the same acceptable delay.

I’ve looked through the documentation but couldn’t find anything related to this issue. I’m sharing my setup and findings here to ask if anyone else has encountered this problem.

Thanks in advance!

**Comment by felipecrs** [comment]
Your configuration seems very wrong:

```diff
go2rtc:
  streams:
    doorbell:
      - echo:/config/scripts/fix_vto_codecs.sh
-       rtsp://admin:admin@192.168.0.100/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
+       rtsp://admin:admin@192.168.0.100/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
```

**Comment by felipecrs** [comment]
And my current recommendation is very different anyway:

```yaml
go2rtc:
  streams:
    doorbell:
      # H264
      - echo:/config/scripts/fix_vto_codecs.sh
        ffmpeg:rtsp://admin:pass@192.168.1.40/cam/realmonitor?channel=1&subtype=0#video=copy
      # AAC, OPUS
      - rtsp://127.0.0.1:8554/doorbell_hd?audio=all
      # PCMA, 2-way audio
      - echo:/config/scripts/fix_vto_codecs.sh
        rtsp://admin:pass@192.168.1.40/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif#media=audio#backchannel=1
```

Please try with my recommendation.

**Comment by felipecrs** [comment]
> I’ve looked through the documentation but couldn’t find anything related to this issue. I’m sharing my setup and findings here to ask if anyone else has encountered this problem.

This is a known issue, yes. It was reported [here](https://github.com/AlexxIT/go2rtc/issues/49#issuecomment-1828701415) at least.

However, I did not notice this issue when using my configuration.

**Comment by Xeudoron** [comment]
> Your configuration seems very wrong:
> 
> ```diff
> go2rtc:
>   streams:
>     doorbell:
>       - echo:/config/scripts/fix_vto_codecs.sh
> -     - rtsp://admin:admin@192.168.0.100/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
> +       rtsp://admin:admin@192.168.0.100/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
> ```

My VTO seems to work a bit differently. I tried using your configuration initially, but it didn’t work, so I made some modifications.

After your quick response and some further testing, I found that keeping the line `- echo:/config/scripts/fix_vto_codecs.sh` prevents Frigate from detecting the camera. Once I removed that script, Frigate was able to recognize the camera, and two-way communication works well.

However, there's still an accumulating delay that I'm looking for a workaround for, but that seems to be out of the scope of this thread.

Thank you

**Comment by felipecrs** [comment]
Can you paste here your final Frigate config again with password redacted?

**Comment by Xeudoron** [comment]
The one I am tinkering with now is based on yours:

```
go2rtc:
  streams:
    doorbell:
      # H264
      - ffmpeg:rtsp://admin:admin@192.168.0.100/cam/realmonitor?channel=1&subtype=0#video=copy
      # AAC, OPUS
      - rtsp://127.0.0.1:8554/doorbell_hd?audio=all
      # PCMA, 2-way audio
      - rtsp://admin:admin@192.168.0.100/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif#media=audio#backchannel=1
    doorbell_hd:
      # H264, AAC, OPUS
      - ffmpeg:rtsp://admin:admin@192.168.0.100/cam/realmonitor?channel=1&subtype=1#video=copy#audio=copy#audio=opus

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&backchannel=0
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/doorbell_hd
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
```

**Comment by felipecrs** [comment]
Sorry, did you say that it's not the outgoing audio which is delayed, but the incoming audio?

- Incoming: audio that comes from the VTO
- Outgoing: audio that comes from your browser and is played by your VTO

**Comment by Xeudoron** [comment]
Yes,

when I speak through my phone or browser, the person on the VTO hears me clearly with just a small, acceptable delay. I can ask a question, and they respond with a nod right away. However, the audio coming back from them to my phone or browser builds up a delay over time.

**Comment by felipecrs** [comment]
Ok, let me rectify myself then:

No, I have never heard of an issue like this before. The issue in go2rtc I mentioned is not related, therefore.

---

Tip:

Update go2rtc to latest version: https://docs.frigate.video/configuration/advanced/#custom-go2rtc-version

---

Question:

Is your CPU usage (or memory) very high during these scenarios? It's important that it's not.

**Comment by felipecrs** [comment]
Another question:

Is your VTO running connected by WiFi?

**Comment by Xeudoron** [comment]
> No, I have never heard of an issue like this before. The issue in go2rtc I mentioned is not related, therefore.

Understand and thank you.

> Update go2rtc to latest version: https://docs.frigate.video/configuration/advanced/#custom-go2rtc-version

I will try that.

> Is your CPU usage (or memory) very high during these scenarios? It's important that it's not.

Tested with top and no, it seems normal.

> Is your VTO running connected by WiFi?

The VTO is connected via PoE and WiFi is disabled.

**Comment by felipecrs** [comment]
Please let me know if a newer go2rtc version helped.

**Comment by felipecrs** [comment]
Try this please:

```yaml
go2rtc:
  streams:
    doorbell:
      - rtsp://admin:admin@192.168.0.100/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
```

But I needed to know which codecs your VTO is serving into each stream. You can open each stream in VLC and then press `Ctrl` + `J`.

**Comment by Xeudoron** [comment]
> Please let me know if a newer go2rtc version helped.

It looks like switching to `go2rtc platform=linux/amd64 revision=dbe9e4a version=1.9.7` helped, Frigate browser and Home Assistant companion app both have acceptable delay and the audio is solid. For testing purposes I have simplified the frigate config.

```
go2rtc:
  streams:
    video_zvonek:
      - rtsp://admin:admin@192.168.0.100/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif

cameras:
  video_zvonek:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/video_zvonek?video=copy&backchannel=0
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy
```

**Comment by felipecrs** [comment]
Great! Here are my final statements:

---

If 2-way audio works, then you may not need `fix_vto_codecs.sh` indeed.

But be aware that maybe this is because `fix_vto_codecs.sh` ran once and now the new codec configuration is saved into your VTO, and that's why it's working (for now).

If that's the case, it should stop working after some days. For some reason, VTO restores this configuration automatically (that's why I call this script on every stream attempt).

---

> I found that keeping the line - echo:/config/scripts/fix_vto_codecs.sh

That's probably because your line was broken, you had split the `fix_vto_codecs.sh` and `rtsp://` into two different array items by adding ` - ` in front of your `rtsp://`.

The correct should be:

```yaml
go2rtc:
  streams:
    doorbell:
      - echo:/config/scripts/fix_vto_codecs.sh rtsp://admin:admin@192.168.0.100/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
```

Or:

```yaml
go2rtc:
  streams:
    doorbell:
      - echo:/config/scripts/fix_vto_codecs.sh
        rtsp://admin:admin@192.168.0.100/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
```

---

This section:

```yaml
    doorbell_hd:
      # H264, AAC, OPUS
      - ffmpeg:rtsp://admin:admin@192.168.0.100/cam/realmonitor?channel=1&subtype=1#video=copy#audio=copy#audio=opus
```

Expects that your VTO will return audio in AAC in the substream. Is that really the case for your VTO? (one of the purposes of `fix_vto_codecs.sh` is to set the substream audio codec to AAC).
